apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${STREAMLIT_NAMESPACE}
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-app
          image: ${STREAMLIT_APP_DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          env:
          - name: MLFLOW_TRACKING_SERVER
            value: ${MLFLOW_TRACKING_SERVER}
          ports:
            - containerPort: ${STREAMLIT_APP_PORT}