apiVersion: v1
kind: Pod
metadata:
  namespace: ${JUPYTER_NAMESPACE}
  name: jupyter-notebook
spec:
  containers:
  - name: jupyter-notebook
    image: jupyter/datascience-notebook:lab-4.0.7
    ports:
    - containerPort: 8888
    env:
    - name: AWS_ACCESS_KEY_ID
      value: ${MLFLOW_AWS_ACCESS_KEY_ID}
    - name: AWS_SECRET_ACCESS_KEY
      value: ${MLFLOW_AWS_SECRET_ACCESS_KEY}
    - name: MLFLOW_TRACKING_SERVER
      value: ${MLFLOW_TRACKING_SERVER}
