apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mlflow
  name: mlflow-postgres-pvc
  labels:
    app: mlflow-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi